# TODO : IMPLEMENT SPRINT MODEL
# NAME,
# DECLARED START DATE,
# DECLARED END DATE,
# ACTUAL START DATE[OPTIONAL],
# ACTUAL END DATE[OPTIONAL],
# RESPONSIBLE MEMBER[OPTIONAL],
# SPRINT STATUS(should be separate ChoiceEnum),
# NOTES
# LINK TO PROJECT
