# TODO : IMPLEMENT TASK MODEL
# NAME, DESCRIPTION
# TASK TYPE[ChoiceEnum=[Task,Story,Bug]]
# RESPONSIBLE MEMBER[OPTIONAL]
# RESPONSIBLE USER[OPTIONAL]
# LINK TO TASK[Optional]
# LINK TO SPRINT[Optional]
# LINK TO PROJECT[Optional]
# ESTIMATED TIME[Optional]
# TASK STATUS - MODEL RELATED TO PROJECT
# TASK PRIORITY - MODEL RELATED TO PROJECT
# TIMEDELTA[Optional](can be written by hand)
